apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
  labels:
    {{- include "appointments.labels" . | nindent 4}}
    app.kubernetes.io/component: appointments
spec:
  replicas: {{ .Values.appointments.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: appointments
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: appointments
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: appointments
          image: {{ .Values.appointments.image }}
          env:
            #- name: DB_URL
              valueFrom:
                secretKeyRef:
                #  name: mongodb
                 # key: appointments_db_url
          ports:
            - name: http
              containerPort: 3335
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3335
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3335