apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "appointments.labels" . | nindent 4}}
type: Opaque
data:
  appointments_db_url: {{ .Values.appointmentsMongoUrl | b64enc }}