apiVersion: v1
kind: Service
metadata: 
  name: appointments
  labels:
    {{- include "appointments.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec: 
  selector:
    app.kubernetes.io/name: appointments
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - targetPort: 3335
      protocol: TCP
      name: http
      port: 3335